import 'package:flutter/material.dart';

class Rules extends StatelessWidget {
  const Rules({super.key});

  @override
  Widget build(BuildContext context) {
    return  Scaffold(
      body: DecoratedBox(
      decoration: const BoxDecoration(
      gradient:  LinearGradient(
      begin: Alignment.topCenter,
      end: Alignment.bottomCenter,
      colors:<Color> [
    Color(0xff360f8e),
    Color(0xffdcdbe3),
    Color(0xffdec5ff),
         ],
       ),
      ),
      child: Stack(
        children: [
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: ListView(
              children: const [
                Text("Base Rules", textAlign: TextAlign.center,
                style: TextStyle(
                  fontWeight: FontWeight.bold,
                  fontSize: 28,
                  color: Colors.white,
                ),
                ),
                Row(children: [
                  Icon(Icons.circle, size: 12,),
                  SizedBox(width: 6),
                  Text("NO MAIN BASES ON THE EXILED LAND MAP!!!",
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                  SizedBox(width: 6),
                  Text("You are allowed 1 main base on the cluster",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                  SizedBox(width: 6),
                  Text("Main bases must be no more than 7500\nbuilding pieces and only one building\n(as in make sure it is all connected)\nDO not spread out or admins will ask you\nremove some of it! use /buildinfo to check\nhow many build pieces you have used",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                  SizedBox(width: 6),
                  Text("No towns, villages, cities or anything else\nthat is unnecessary!",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                  SizedBox(width: 6),
                  Text("MAX 700 placeable's for main bases",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black),
                SizedBox(height: 8,),
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children:[
                  Text("Outposts",
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 28,
                    color: Colors.white
                  ),
                  textAlign: TextAlign.center,
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                  SizedBox(width: 6),
                  Text("Outpost bases can be no bigger than 7x7x7\nand no more than 500 building pieces",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("Max 60 placeables at any outpost",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(
                  children: [Icon(Icons.circle, size: 12,),
                  SizedBox(width: 6),
                  Text("No more than 30 placed thralls/pets for\nclans and solo at main bases, 5 at outposts.",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                  Text("Building Rules",
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 28,
                    color: Colors.white,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("Absolutely NO foundation stacking No excuses!",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("You must make sure you are at least 50\nfoundation lengths away from the next base",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("Do not build away from your base\nNo wheels of pain /foundations, elevators\nor bedrolls/beds anywhere apart from\nyour base! (use /heatmap to see where you\nhave stuff placed)",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("You are allowed a maximum of 4 of\nany of the similar type of crating bench at\nyour main base, and a maximum of 1 of each\nat your outposts! if you use the beyond\nstations (p) benches these combine all\nmods and vanilla into one bench!",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("Max 2 Wheels of pain per clan (1 if solo)\nMax 2 Mines per clan (1 if solo)\nMax 2 Animal pens (this includes the dragon\nlair & any other animal bench) per clan\n(1 if solo\nMax 6 fishing traps (or similar workbench)\nper clan!",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("1 religious altar allowed per base, per map.",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("2 Dispatch board per clan per map.",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("NO farms/planters or anything used to grow\nplants on the EL map, you may have\n5 planters at each base on each map.",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                  Text("Basic Rules",
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 28,
                    color: Colors.white
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("You MUST make a clan as soon as you can\nAdmins can't help you if you aren't in a clan.",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("Your discord and in game name must be\nthe same please.",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("There are no decay timers on this server\nbut if you are inactive for more than 14 days\nyour base/character will be deleted, so\nif you are going to be away for more than 14\ndays please post in the ⁠absence channel\nwhere you will be allowed an extra 14 days\nbefore your base is removed! You must log\nonto each map you have a base on, within\nthe 2-week timer to avoid losing your base.",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("NO map rooms to be placed in the world\nyou can /warp portal to get around the world!",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("Do NOT /sethome or place a bedroll in any\ndungeon or boss area.",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("No blocking of boss spawns",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("No building in POI (they will be removed\nwithout warning) this includes within view\ndistance of warp points!",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("Do not leave pets/thralls away from your\nbase. if admins find them out in the world\nthey will be removed without warning.",
                  style: TextStyle(
                    fontSize: 14,
                  ),
                  ),
                ],
                ),
                Divider(height: 6, color: Colors.black,),
                SizedBox(height: 8,),
                Row(children: [Icon(Icons.circle, size: 12,),
                SizedBox(width: 6),
                  Text("Ascension weapons/ accessories are NOT\nto be sold/given away. The same applies\nfor any custom quests which rewards you\na one-time mega weapon/armour such as\ncorvinas bow or dark infused armour.",
                  style: TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.bold,
                  ),
                  ),
                ],
                ),
              ],
            ),
          )
        ],
      ),
      ),
    );
  }
}
